version: '3.8'

services:
  extract-service:
    build: ./services/extract
    ports:
      - "8000:8000"
    networks:
      - psx-etl-network

  transform-service:
    build: ./services/transform
    ports:
      - "8001:8001"
    depends_on:
      - extract-service
    networks:
      - psx-etl-network

  visualization-service:
    build: ./services/visualization
    ports:
      - "8002:8002"
    depends_on:
      - transform-service
    environment:
      - TRANSFORM_SERVICE_URL=http://transform-service:8001
    networks:
      - psx-etl-network
  scheduler-service:
    build: ./services/scheduler
    ports:
      - "8004:8004"
    depends_on:
      extract-service:
        condition: service_healthy
      transform-service:
        condition: service_healthy
      visualization-service:
        condition: service_healthy
    environment:
      - EXTRACT_SERVICE_URL=http://extract-service:8000
      - TRANSFORM_SERVICE_URL=http://transform-service:8001
      - VISUALIZATION_SERVICE_URL=http://visualization-service:8002
    networks:
      - psx-etl-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8004/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  postgres-db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: psx_user
      POSTGRES_PASSWORD: psx_password123
      POSTGRES_DB: psx_warehouse
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - psx-etl-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U psx_user -d psx_warehouse"]
      interval: 30s
      timeout: 10s
      retries: 5

  load-service:
    build: ./services/load
    ports:
      - "8003:8003"
    depends_on:
      postgres-db:
        condition: service_healthy
      transform-service:
        condition: service_started
    env_file:
      - ./services/load/.env
    networks:
      - psx-etl-network

networks:
  psx-etl-network:
    driver: bridge

volumes:
  postgres_data:
