version: '3.8'

services:
  extract-service:
    build: ./services/extract
    ports:
      - "8000:8000"
    networks:
      - psx-etl-network

  transform-service:
    build: ./services/transform
    ports:
      - "8001:8001"
    depends_on:
      - extract-service
    networks:
      - psx-etl-network

  visualization-service:
    build: ./services/visualization
    ports:
      - "8002:8002"
    depends_on:
      - transform-service
    environment:
      - TRANSFORM_SERVICE_URL=http://transform-service:8001
    networks:
      - psx-etl-network
  scheduler-service:
    build: ./services/scheduler
    ports:
      - "8004:8004"
    depends_on:
      extract-service:
        condition: service_healthy
      transform-service:
        condition: service_healthy
      visualization-service:
        condition: service_healthy
    environment:
      - EXTRACT_SERVICE_URL=http://extract-service:8000
      - TRANSFORM_SERVICE_URL=http://transform-service:8001
      - VISUALIZATION_SERVICE_URL=http://visualization-service:8002
    networks:
      - psx-etl-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8004/health"]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  psx-etl-network:
    driver: bridge
