apiVersion: v1
kind: Service
metadata:
  name: visualization-service
spec:
  selector:
    app: visualization
  ports:
    - protocol: TCP
      port: 8002 # Expose port 8002
      targetPort: 8002 # Target port 8002 on the pod
