apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: psx-etl-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  rules:
  - host: etl-cluster-671e80eceac83a1671e7575023369992-0000.us-south.containers.appdomain.cloud
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: visualization-service
            port:
              number: 8002

      - path: /_dash-component-suites(/|$)(.*)
        pathType: Prefix
        backend:
          service:
            name: visualization-service
            port:
              number: 8002

      - path: /_dash-layout(/|$)(.*)
        pathType: Prefix
        backend:
          service:
            name: visualization-service
            port:
              number: 8002

      - path: /_dash-dependencies(/|$)(.*)
        pathType: Prefix
        backend:
          service:
            name: visualization-service
            port:
              number: 8002

      - path: /_favicon(.*)
        pathType: Prefix
        backend:
          service:
            name: visualization-service
            port:
              number: 8002

      - path: /scheduler(/|$)(.*)
        pathType: Prefix
        backend:
          service:
            name: scheduler-service
            port:
              number: 8004

      - path: /transform(/|$)(.*)
        pathType: Prefix
        backend:
          service:
            name: transform-service
            port:
              number: 8001

      - path: /load(/|$)(.*)
        pathType: Prefix
        backend:
          service:
            name: load-service
            port:
              number: 8003

      - path: /extract(/|$)(.*)
        pathType: Prefix
        backend:
          service:
            name: extract-service
            port:
              number: 8000
