apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: database
type: Opaque
stringData:   # plaintext (K8s will encode it automatically)
  POSTGRES_DB: etldb
  POSTGRES_USER: etluser
  POSTGRES_PASSWORD: etlpass123
  DATABASE_URL: "postgresql://etluser:etlpass123@postgres.database.svc.cluster.local:5432/etldb"

